name: build-and-release
on:
  pull_request:
  push:
    branches:
      - main # Replace with your main branch name if different

jobs:
  build:
    strategy:
      matrix:
        java: [21] # You can add more Java versions here if needed
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "microsoft"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Create Release
        if: matrix.java == '21' # Create release only for builds with Java 21
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Specify your tag version here
          release_name: Release v1.0.0 # Name of the release
          body: |
            Release v1.0.0
            - Describe what's new in this release

          draft: false # Change to true if you want to create a draft release
          prerelease: false # Set to true for prereleases

